### PR TITLE
gh-revision: initial implementation

### PR DESCRIPTION
**Pull request by r-bk**
- **gh-revision: initial implementation**
- **github: add Build workflow**
- **github: add Release workflow**
- **gh-revision: add README.md**

### CODE REVIEW

**Comment by r-bk** [comment]
Revision 1
---


[//]: # (gh-revision-body-start)

First review revision.
It is possible to add custom message like this using `gh revision create -e`.


[//]: # (gh-revision-body-end)

**Compare**
- [0..1](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..da92d5eebeea58886c98fd15586e9126984eaa7c)

**CC** @horomena


[//]: # (gh-revision:{"number":1,"hash":"da92d5eebeea58886c98fd15586e9126984eaa7c","baseHash":"756686231693a31574c39a4e714578848bd85c03"})

**Review by horomena — APPROVED** [review]

**Comment by horomena** [comment]
@r-bk probably worth adding a *short* readme that explains how to install and use it

**Comment by r-bk** [comment]
> @r-bk probably worth adding a **short** readme that explains how to install and use it

Working exactly on that. Will send another revision shortly.

**Comment by r-bk** [comment]
Revision 2
---


[//]: # (gh-revision-body-start)

Added a README.md.
Fixed the tool description.


[//]: # (gh-revision-body-end)

**Compare**
- [1..2](https://github.com/hushsecurity/gh-revision/compare/da92d5eebeea58886c98fd15586e9126984eaa7c..5a19cc83e558bc5add9d1c5c8a0c6f36f229baea)
- [0..1](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..da92d5eebeea58886c98fd15586e9126984eaa7c), [0..2](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..5a19cc83e558bc5add9d1c5c8a0c6f36f229baea)



[//]: # (gh-revision:{"number":2,"hash":"5a19cc83e558bc5add9d1c5c8a0c6f36f229baea","baseHash":"756686231693a31574c39a4e714578848bd85c03"})

**Comment by r-bk** [comment]
Revision 3
---


[//]: # (gh-revision-body-start)

Added a section for `Aliases` in README.md.


[//]: # (gh-revision-body-end)

**Compare**
- [2..3](https://github.com/hushsecurity/gh-revision/compare/5a19cc83e558bc5add9d1c5c8a0c6f36f229baea..076d15aa44a0935d4882350e9744072d0b5ac5bf)
- [1..2](https://github.com/hushsecurity/gh-revision/compare/da92d5eebeea58886c98fd15586e9126984eaa7c..5a19cc83e558bc5add9d1c5c8a0c6f36f229baea), [1..3](https://github.com/hushsecurity/gh-revision/compare/da92d5eebeea58886c98fd15586e9126984eaa7c..076d15aa44a0935d4882350e9744072d0b5ac5bf)
- [0..1](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..da92d5eebeea58886c98fd15586e9126984eaa7c), [0..3](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..076d15aa44a0935d4882350e9744072d0b5ac5bf)



[//]: # (gh-revision:{"number":3,"hash":"076d15aa44a0935d4882350e9744072d0b5ac5bf","baseHash":"756686231693a31574c39a4e714578848bd85c03"})

**Comment by r-bk** [comment]
Revision 4
---


[//]: # (gh-revision-body-start)

Fixed README


[//]: # (gh-revision-body-end)

**Compare**
- [3..4](https://github.com/hushsecurity/gh-revision/compare/076d15aa44a0935d4882350e9744072d0b5ac5bf..e9b1fdc59274876a9f3ce1c146fe5793e56132a2)
- [2..3](https://github.com/hushsecurity/gh-revision/compare/5a19cc83e558bc5add9d1c5c8a0c6f36f229baea..076d15aa44a0935d4882350e9744072d0b5ac5bf), [2..4](https://github.com/hushsecurity/gh-revision/compare/5a19cc83e558bc5add9d1c5c8a0c6f36f229baea..e9b1fdc59274876a9f3ce1c146fe5793e56132a2)
- [1..2](https://github.com/hushsecurity/gh-revision/compare/da92d5eebeea58886c98fd15586e9126984eaa7c..5a19cc83e558bc5add9d1c5c8a0c6f36f229baea), [1..4](https://github.com/hushsecurity/gh-revision/compare/da92d5eebeea58886c98fd15586e9126984eaa7c..e9b1fdc59274876a9f3ce1c146fe5793e56132a2)
- [0..1](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..da92d5eebeea58886c98fd15586e9126984eaa7c), [0..4](https://github.com/hushsecurity/gh-revision/compare/756686231693a31574c39a4e714578848bd85c03..e9b1fdc59274876a9f3ce1c146fe5793e56132a2)

**CC** @horomena


[//]: # (gh-revision:{"number":4,"hash":"e9b1fdc59274876a9f3ce1c146fe5793e56132a2","baseHash":"756686231693a31574c39a4e714578848bd85c03"})

**Pull request merged**
